services:
  - type: web
    name: reviewgpt-backend
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_DB_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: EMBEDDING_DIMENSION
        value: "1024"
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: APP_ENV
        value: production
